title: 兵庫県西脇市
description: 兵庫県西脇市内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1z9hGpLh1iAEYW3LyArFiSeQvRQFqj3FrI8wApf6OsbE/export?format=csv&gid=0
repository: https://github.com/junonet/app/
form_url: https://docs.google.com/forms/d/e/1FAIpQLSfGgDTbTqaB7la8-K6sk4YAeWgTne3OcO7pDoSRlnRRKz5wPA/viewform
